### ISSUE TITLE
Facilitate developpement (networking, ipset, root rights)

### ISSUE THREAD

**Issue by AntoninCamus** [InsaLan/langate2000#15]
To facilitate development, **if server is in debug**, the lack of root rights or of the package ipset should not crash, and instead print a big warn / error but absorb it. 

E.g : 
- networking library throw an exception when root is not present or ipset is not installed
- when importing the library, views.py replace it by knockoff functions and print a big warning if server is in DEBUG. If not, it crashes.

**Comment by ShiroUsagi-san** [comment]
And maybe detect when a user is in local and debug to  simulate Mac and ip address to have a working gate in local dev environment

**Comment by AntoninCamus** [comment]
I dont think so, that would increase complexity, and an invalid Mac / IP
would not cause any issues.
The other possibility is making an Docker or Vagrant to simplify dev.

Le jeu. 28 févr. 2019 à 10:14, Dyingcell <notifications@github.com> a
écrit :

**Comment by ShiroUsagi-san** [comment]
so maybe, we should distribute one already configured (via a dockerfile for example) to make the dev easier.

**Comment by darkgallium** [comment]
- We eased development by providing two docker environments : one for production, one for development (06ad704 and a1b0bf1)
- Networking code was separated from the website code itself (see the InsaLan/langate2000-netcontrol submodule)
- Networking code code was refactored to be maintainable (InsaLan/langate2000-netcontrol#1)
I consider this to be closed.
